"""Training pipeline for the strict and surrogate detectors.

Kept as importable modules rather than notebook cells so the pipeline can be
read, diffed and unit-tested. The notebooks in `training/` are thin drivers
generated by `build_notebooks.py`.
"""
